using System;
using System.Collections.Generic;
using System.Text;

namespace windows_audit
{
    class CDROMDrive
    {
        Int16 Availability;
        Int16[] Capabilities;
        string[] CapabilityDescriptions;
        string Caption;
        string CompressionMethod;
        Int32 ConfigManagerErrorCode;
        bool ConfigManagerUserConfig;
        string CreationClassName;
        Int64 DefaultBlockSize;
        string Description;
        string DeviceID;
        string Drive;
        bool DriveIntegrity;
        bool ErrorCleared;
        string ErrorDescription;
        string ErrorMethodology;
        Int16 FileSystemFlags;
        Int32 FileSystemFlagsEx;
        string Id;
        DateTime InstallDate;
        Int32 LastErrorCode;
        string Manufacturer;
        Int64 MaxBlockSize;
        Int32 MaximumComponentLength;
        Int64 MaxMediaSize;
        bool MediaLoaded;
        string MediaType;
        string MfrAssignedRevisionLevel;
        Int64 MinBlockSize;
        string Name;
        bool NeedsCleaning;
        Int32 NumberOfMediaSupported;
        string PNPDeviceID;
        Int16[] PowerManagementCapabilities;
        bool PowerManagementSupported;
        string RevisionLevel;
        Int32 SCSIBus;
        Int16 SCSILogicalUnit;
        Int16 SCSIPort;
        Int16 SCSITargetId;
        string SerialNumber;
        Int64 Size;
        string Status;
        Int16 StatusInfo;
        string SystemCreationClassName;
        string SystemName;
        double TransferRate;
        string VolumeName;
        string VolumeSerialNumber;
    }
}
