using System;
using System.Collections.Generic;
using System.Text;

namespace WindowsAudit
{
    class GPU
    {
        Int16[] AcceleratorCapabilities;
        string AdapterCompatibility;
        string AdapterDACType;
        Int32 AdapterRAM;
        Int16 Availability;
        string[] CapabilityDescriptions;
        string Caption;
        Int32 ColorTableEntries;
        Int32 ConfigManagerErrorCode;
        bool ConfigManagerUserConfig;
        string CreationClassName;
        Int32 CurrentBitsPerPixel;
        Int32 CurrentHorizontalResolution;
        Int64 CurrentNumberOfColors;
        Int32 CurrentNumberOfColumns;
        Int32 CurrentNumberOfRows;
        Int32 CurrentRefreshRate;
        Int16 CurrentScanMode;
        Int32 CurrentVerticalResolution;
        string Description;
        string DeviceID;
        Int32 DeviceSpecificPens;
        Int32 DitherType;
        DateTime DriverDate;
        string DriverVersion;
        bool ErrorCleared;
        string ErrorDescription;
        Int32 ICMIntent;
        Int32 ICMMethod;
        string InfFilename;
        string InfSection;
        DateTime InstallDate;
        string InstalledDisplayDrivers;
        Int32 LastErrorCode;
        Int32 MaxMemorySupported;
        Int32 MaxNumberControlled;
        Int32 MaxRefreshRate;
        Int32 MinRefreshRate;
        bool Monochrome;
        string Name;
        Int16 NumberOfColorPlanes;
        Int32 NumberOfVideoPages;
        string PNPDeviceID;
        Int16[] PowerManagementCapabilities;
        bool PowerManagementSupported;
        Int16 ProtocolSupported;
        Int32 ReservedSystemPaletteEntries;
        Int32 SpecificationVersion;
        string Status;
        Int16 StatusInfo;
        string SystemCreationClassName;
        string SystemName;
        Int32 SystemPaletteEntries;
        DateTime TimeOfLastReset;
        Int16 VideoArchitecture;
        Int16 VideoMemoryType;
        Int16 VideoMode;
        string VideoModeDescription;
        string VideoProcessor;
    }
}
